name: Staging Packager

on:
  pull_request:
    branches: ['staging']

jobs:
  build-test-package:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22.x]
        package_dir: ${{ github.workspace }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run test
    - run: npm run package
      working-directory: ${{ matrix.package_dir }}
    - name: Upload artifact to ${{ matrix.package_dir }}
      uses: actions/upload-artifact@v2
      with:
        path: ${{ matrix.package_dir }}
